name: keras
channels:
  - anaconda
  - defaults
dependencies:
  - scipy=1.2.1
  - _tflow_select=2.2.0
  - bzip2=1.0.6
  - keras=2.2.4
  - keras-base=2.2.4
  - keras-preprocessing=1.1.0
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pandas=0.20.3
  - scikit-image=0.13.0
  - scikit-learn=0.20.2
  - seaborn=0.9.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - zlib=1.2.11

